# Use Java 17 JDK
FROM eclipse-temurin:17-jdk-alpine

# Set working directory inside container
WORKDIR /app

# Copy the built jar into container
COPY target/URLshortner-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8082 (or whatever your server.port is)
EXPOSE 8083

# Run the Spring Boot jar
ENTRYPOINT ["java","-jar","app.jar"]
